#!/bin/bash
# Autogenerated speak.sh configured for your local Piper setup using paplay and file caching
TEXT="$1"
CACHE_FILE="$2"

if [ -f "$CACHE_FILE" ]; then
    # Instant playback from cache!
    paplay "$CACHE_FILE"
else
    # First time: generate and cache, then play
    echo "$TEXT" | /home/user/piper/piper --model /home/user/piper/es_MX-claude-high.onnx --output_file "$CACHE_FILE" && paplay "$CACHE_FILE"
fi
